// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251106034752_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique();

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tin tức công nghệ mới nhất",
                            Name = "Công nghệ",
                            UrlSlug = "cong-nghe"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Khám phá và nghiên cứu khoa học",
                            Name = "Khoa học",
                            UrlSlug = "khoa-hoc"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Tin tức về phim ảnh, âm nhạc",
                            Name = "Giải trí",
                            UrlSlug = "giai-tri"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Tin tức tài chính và kinh doanh",
                            Name = "Kinh tế",
                            UrlSlug = "kinh-te"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cập nhật các sự kiện thể thao mới nhất",
                            Name = "Thể thao",
                            UrlSlug = "the-thao"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PostedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Published")
                        .HasColumnType("bit");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UrlSlug")
                        .IsUnique();

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "AI đang dần trở thành một phần không thể thiếu...",
                            Meta = "AI, công nghệ, tương lai",
                            PostedOn = new DateTime(2025, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Cách AI tác động đến các ngành nghề trong tương lai.",
                            Title = "AI thay đổi thế giới như thế nào",
                            UrlSlug = "ai-thay-doi-the-gioi"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Kính viễn vọng James Webb giúp con người nhìn xa hơn...",
                            Meta = "khoa học, vũ trụ",
                            PostedOn = new DateTime(2025, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Các nhà khoa học đã phát hiện hành tinh mới...",
                            Title = "Khám phá vũ trụ với kính viễn vọng mới",
                            UrlSlug = "vu-tru-voi-kinh-vien-vong-moi"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Nhiều startup công nghệ ra đời, thu hút vốn đầu tư lớn...",
                            Meta = "startup, kinh tế",
                            PostedOn = new DateTime(2025, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Khởi nghiệp đang là xu hướng mạnh tại Việt Nam.",
                            Title = "Doanh nghiệp Việt và làn sóng Startup",
                            UrlSlug = "doanh-nghiep-viet-startup"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Công nghệ chuỗi khối mang lại sự minh bạch và bảo mật...",
                            Meta = "blockchain, tài chính",
                            PostedOn = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Blockchain đang thay đổi cách giao dịch tài chính.",
                            Title = "Xu hướng Blockchain trong tài chính",
                            UrlSlug = "blockchain-trong-tai-chinh"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Các vận động viên Việt Nam đạt thành tích ấn tượng...",
                            Meta = "thể thao, olympic",
                            PostedOn = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Published = true,
                            ShortDescription = "Việt Nam giành huy chương tại Olympic Paris.",
                            Title = "Olympic Paris 2024 - niềm tự hào thể thao Việt",
                            UrlSlug = "olympic-paris-2024"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PostTagMap", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTagMap");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            TagId = 1
                        },
                        new
                        {
                            PostId = 1,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 2
                        },
                        new
                        {
                            PostId = 3,
                            TagId = 3
                        },
                        new
                        {
                            PostId = 4,
                            TagId = 4
                        },
                        new
                        {
                            PostId = 5,
                            TagId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UrlSlug")
                        .IsUnique();

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Trí tuệ nhân tạo",
                            Name = "AI",
                            UrlSlug = "ai"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Học máy và ứng dụng",
                            Name = "Machine Learning",
                            UrlSlug = "machine-learning"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Khởi nghiệp sáng tạo",
                            Name = "Startup",
                            UrlSlug = "startup"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Công nghệ chuỗi khối",
                            Name = "Blockchain",
                            UrlSlug = "blockchain"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Bài viết về văn hóa và xã hội",
                            Name = "Văn hóa",
                            UrlSlug = "van-hoa"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.PostTagMap", b =>
                {
                    b.HasOne("Domain.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Domain.Entities.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
